export {default as DefaultLayout} from './DefaultLayout'
export {default as CategoryLayout} from './CategoryLayout'
export {default as ProductDetailLayout} from './ProductDetailLayout'
export {default as ProductLayout} from './ProductLayout'
export {default as NoneLayout} from './NoneLayout'